name: RSpawn
version: 1
main: me.rejomy.rspawn.Main
api-version: 1.13
softdepend:
  - Multiverse-Core
  - MultiWorld
  - AntiRelog
commands:
  spawn:
    aliases:
      - spaw
      - spa
      - span
      - spwn
      - sawn
      - pawn
      - s[awn
      - спавн
      - спв
      - спав
      - спан
      - спвн
      - савн
      - павн
  kill:
    aliases:
      - killplayer
      - playerkill
    permission: rspawn.command.kill